### ISSUE TITLE
Make permissions and ownership? configurable while persisting

### ISSUE THREAD

**Issue by xaverdh** [Stebalien/tempfile#137] opened 2021-01-07 10:19 UTC
Related issues: #30, #114

It might not be possible to support on all platforms, but it would still be nice to have it at least on unix. This issue is specifically about permissions / ownership of the persisted file rather than the temporary file, but I would also be quite happy with an option to configure permissions on the temporary, if they get carried over to the persisted file.

My use case is to atomically write files with given permissions / ownership by first writing to a temporary file and then persisting it (relying on rename likely being atomic), so just changing these after the fact will slightly defeat the purpose..

**Comment by xaverdh** [comment] 2021-01-07 10:28
Implementation wise, I think the most realistic approach is to make permissions on the temporary file configurable and then make persist keep those. Ownership could be configured through the `Builder`, but would only come into effect when persisting.

On Linux this would correspond to passing `O_TMPFILE`, but without `O_EXCL` and creating it with given mode. Then just before persisting it with `linkat` you would call `fchmod` to adjust ownership.
I don't know how well this fits with other platforms though..

**Comment by Stebalien** [comment] 2021-01-17 19:12
As far as I know, persist _should_ keep the permissions. So you should be able to:

1. Create a named temporary file.
2. Chmod the temporary file.
3. Call persist.

> On Linux this would correspond to passing O_TMPFILE, but without O_EXCL and creating it with given mode. Then just before persisting it with linkat you would call fchmod to adjust ownership.

This library does not support persisting temporary files created with `O_TMPFILE`, unfortunately. I'd like to implement this, but I have a policy of only providing features that are truly cross-platform (linux, windows, macos, freebsd), including sharing equivalent security guarantees.

**Comment by D1plo1d** [comment] 2021-05-08 18:40
> This library does not support persisting temporary files created with `O_TMPFILE`, unfortunately. I'd like to implement this, but I have a policy of only providing features that are truly cross-platform (linux, windows, macos, freebsd), including sharing equivalent security guarantees.

Would it be possible to remove the `O_EXCL` flag entirely? Is there a security difference from eg. windows or some other OS if it is removed? It appears that according to the [gnu libc docs](https://www.gnu.org/software/libc/manual/html_node/Open_002dtime-Flags.html) `O_EXCL | O_TMPFILE` only serve to prevent persisting tempfiles and it's removal would allow developers to persist tempfiles externally to `tempfile.rs` using `nix`.

For example without `O_EXCL` the following works:

```rust
tmpfile::tmpfile();
let tmp_file_path = format!("/proc/self/fd/{}", tmp_file.as_raw_fd());

nix::unistd::linkat(
    None,
    &tmp_file_path[..],
    None,
    &file_path[..],
    nix::unistd::LinkatFlags::SymlinkFollow,
)?;
```

**Comment by Stebalien** [comment] 2021-05-10 03:04
IIRC, the problem is MacOS and the BDSs. On those platforms, temporary
files are implemented by creating then immediately unlinking, and
there's no way to "relink" (last I checked).

**Comment by Byron** [comment] 2023-04-20 16:39
For `gitoxide` it would be most beneficial if the mode could be set for the temporary file at creation time to avoid a follow-up `chmod` call for increased performance by reducing the amount of syscalls.

Git does the same by default.

As per the policy of providing cross-platform features only, implementing this would be out of scope though. Would you be open to a contribution if this was an exceptional case?

Thank you 🙏

**Comment by Stebalien** [comment] 2024-08-06 20:00
It's now possible to set the permissions in the builder, so I believe the core issue here is fixed.

**Closed by Stebalien** 2024-08-06 20:00 UTC
